default indicators can now accept custom text
EdsonBueno/infinite_scroll_pagination pull request #275
Opened 2023-07-26 08:24 UTC by abubakarmvp

for translation purpose i updated the default indicator pages and also export them to be available in the app

2023-08-17 21:08 UTC, clragon commented
could you update your PR to only include changes to the files necessary?

2023-08-18 07:20 UTC, abubakarmvp commented
hi, 
i updated the PR

2023-08-18 15:17 UTC, clragon requested changes

2023-08-18 15:17 UTC, clragon commented on example/ios/Podfile.lock
> -COCOAPODS: 1.11.3
please remove changes to other files

2023-08-18 15:17 UTC, clragon commented on example/lib/samples/beer_list_view.dart
> +            ),
is there a reason you have added this? 
this should be the default already, right?

2023-08-18 15:17 UTC, clragon commented on lib/src/widgets/helpers/default_status_indicators/first_page_exception_indicator.dart
> +    required this.message,
is there a reason you have nmade this required?

2023-08-18 15:17 UTC, clragon commented on lib/src/widgets/helpers/default_status_indicators/first_page_exception_indicator.dart
> +    this.tryAgainBtnTxt,
could this maybe named in a way that fits the other parameter names?
e.g. `tryAgainText`

2023-08-18 15:17 UTC, clragon commented on lib/src/widgets/helpers/default_status_indicators/first_page_progress_indicator.dart
> +  final bool adaptive;
could you add some spaces around this variable?

2023-08-18 15:17 UTC, clragon commented on lib/src/widgets/helpers/default_status_indicators/new_page_error_indicator.dart
> +    this.errorMsg = 'Something went wrong. Tap to try again.',
could we use full names for variables?
e.g. `errorMessage`?

2023-08-18 15:17 UTC, clragon commented on lib/src/widgets/helpers/default_status_indicators/new_page_error_indicator.dart
> +  final String errorMsg;
could you add a space here?

2023-08-18 15:17 UTC, clragon commented on lib/src/widgets/helpers/default_status_indicators/new_page_progress_indicator.dart
> +  final bool adaptive;
could you add a space above here?

2023-08-18 15:17 UTC, clragon commented on lib/src/widgets/helpers/default_status_indicators/no_items_found_indicator.dart
> +  final String title;
could you add some spaces here?

2023-08-21 07:29 UTC, abubakarmvp commented
hi,
i updated the PR. can please check it.

2024-02-19 21:29 UTC, clragon commented
This PR requires exporting the default page indicators.
I believe that might be undesirable, as indicated in #36.

#216 might be a better way of solving this.

2024-02-19 21:29 UTC, closed without merging